# Generated by Django 4.1 on 2023-05-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetups", "0004_participant_meetup_participants"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetup",
            name="date",
            field=models.DateField(default="2023-05-06"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="meetup",
            name="organizer_email",
            field=models.EmailField(
                default="omkarlpatil64@gmail.com", max_length=254),
            preserve_default=False,
        ),
    ]
