# Generated by Django 4.1 on 2023-05-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetups", "0008_remove_meetup_date_remove_meetup_organizer_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetup",
            name="date",
            field=models.DateField(default="2023-05-06"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="meetup",
            name="organizer_email",
            field=models.EmailField(default="omkar@gmail.com", max_length=254),
            preserve_default=False,
        ),
    ]
